### ISSUE TITLE
Token invalid error

### ISSUE THREAD

**Issue by fpor** [nulledituriel/discord-dmall#1]
Hello I get TOKEN_INVALID error even though I'm using the correct token I've checked multiple times.
Hopefully you can help me out, error included below.

`Collection [Map] {
  'dm' => { name: 'dm', description: 'DM.', execute: [Function: execute] } }
(node:7975) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/discord-dmall/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at Client.login (/discord-dmall/node_modules/discord.js/src/client/Client.js:223:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:7975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by nulledituriel** [comment]
Your token is probably outdated or invalid. Try to generate a new one from the discord developer panel, and check the syntax insade the `config.js` file.

**Comment by fpor** [comment]
> discord developer panel
Oh this is for a discord bot token? thought it was for user token usage.
Unfortunately worthless for me as I cannot invite bots to other people's servers, however if it worked on user token I could just invite the user.
